title: "CS 212 - Artificial Intelligence Programming 1"
description: "Course materials, lecture notes, and assignments for CS 212: Artificial Intelligence Programming 1."
theme: jekyll-theme-primer
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
